---
- name: Uninstall KVM
  hosts: "{{ kvm_hosts | default('localhost') }}"
  become: true
  tasks:
    - name: Include uninstall tasks
      ansible.builtin.include_role:
        name: kvm
        tasks_from: uninstall.yml
