---
- name: Setup KVM
  hosts: "{{ kvm_hosts | default('localhost') }}"
  become: true
  tasks:
    - name: Include install tasks
      ansible.builtin.include_role:
        name: kvm
        tasks_from: install.yml
