---
# handlers for kvm role

- name: Reload KVM modules
  ansible.builtin.shell: |
    rmmod kvm_intel || true
    rmmod kvm_amd || true
    rmmod kvm || true
    modprobe kvm
    modprobe kvm_intel || true
    modprobe kvm_amd || true

- name: Restart libvirt
  ansible.builtin.service:
    name: libvirtd
    state: restarted

- name: Update GRUB
  ansible.builtin.command: update-grub

- name: Update Initramfs
  ansible.builtin.command: update-initramfs -u -k all
